### ISSUE TITLE
Именование 

### ISSUE THREAD

**Issue by Olga-Skoroded** [grzdrz/FSD_Task2#10]
Следует давать более осмысленные имена и избегать перечисления 
![img](https://user-images.githubusercontent.com/68814270/90330806-d7d24380-dfd9-11ea-969a-a7ac9a1f71d5.png)

**Comment by Olga-Skoroded** [comment]
Проверь именование обработчиков событий 
![event listeners](https://user-images.githubusercontent.com/68814270/91553587-dc8ee400-e957-11ea-8034-19bf6813b52b.png)

> Обработчики событий для БЭМ-элементов, а также для компонент, вложенных в БЭМ-элементы, именуются по шаблону `handleElementNameEventName`, где `ElementName` - имя БЭМ-элемента.

**Comment by Olga-Skoroded** [comment]
А вот этот метод вроде бы обработчиком события не является, может убрать тогда handle? 
![close dropdown](https://user-images.githubusercontent.com/68814270/91553751-19f37180-e958-11ea-928e-24d767c73db9.png)

**Comment by Olga-Skoroded** [comment]
Тут вот в `radio-button-image` каждый раз картинку ищу, хотя ее там нет вроде бы. Давай тоже как-нибудь переименуем) 
![radio-image](https://user-images.githubusercontent.com/68814270/91553895-5d4de000-e958-11ea-8331-81e443e65cea.png)

**Comment by Olga-Skoroded** [comment]
Еще в js поправь пожалуйста именования по типу` _move`, `_update`, `list`. Непонятно, что именно move и update, и что там в этом list'e)

**Comment by Olga-Skoroded** [comment]
Тут, мне кажется, plus и minus тоже стоит переименовать, name не нашла, где используется 
![dropdown](https://user-images.githubusercontent.com/68814270/91958817-0a966e80-ed32-11ea-8536-3e18477c285f.png)

**Comment by grzdrz** [comment]
name в классе dropdown используется, но навсякий все равно обернул в геттер

**Comment by Olga-Skoroded** [comment]
А зачем там нижнее подчеркивание у свойств добавилось? Имя name не информативное совершенно, переименуй как-нибудь)
