### ISSUE TITLE
Px to rem

### ISSUE THREAD

**Issue by Olga-Skoroded** [grzdrz/FSD_Task2#6]
Лучше использовать rem'ы, т.к. изменив размер шрифта одного элемента, можно будет изменить масштаб всей верстки

**Comment by grzdrz** [comment]
В качестве базового размера шрифта можно взять любое число или есть строго определенное? 
Т.е. могу ли я указать
font{
  font-size: 1px;
} 
чтобы в остальном коде просто поменять окончание "px" на "rem"?

**Comment by Olga-Skoroded** [comment]
Нет, так делать не надо) Стандартный размер шрифта для html 14-16px. Для удобства можно использовать расширение "px to rem", в vscode точно есть такое
